### ISSUE TITLE
print out url when running locally. 

### ISSUE THREAD

**Issue by etosch** [prakhar1989/react-surveyman#10]
Not sure where to navigate to after executing `npm run watch`!

**Comment by prakhar1989** [comment]
`npm run watch` is responsible only for compiling the js files incrementally. You need to serve the files using a simple server e.g. `python -m SimpleHTTPServer` to view the index.html.

I will update the `README` with this info. Let me know if you face any issues.

**Comment by etosch** [comment]
Ah, okay. I thought you might the using node to run the server.

**Comment by prakhar1989** [comment]
Updated readme with instructions. Fixed in https://github.com/prakhar1989/react-surveyman/commit/5b10e2532cc1fbdd5f515e46b68ce381aa3a70fa
