### ISSUE TITLE
update package info

### ISSUE THREAD

**Issue by etosch** [prakhar1989/react-surveyman#11]
This is minor, but the package info still says it's running "react-shopping-cart-demo" and that the author is "".

**Comment by prakhar1989** [comment]
Ah. My bad. I picked the `package.json` file from [this](https://github.com/prakhar1989/react-shopping-cart) project when starting out. Fixed in https://github.com/prakhar1989/react-surveyman/commit/e04c077d94181448e9d226eef4f8a698a4be329d
