### ISSUE TITLE
Add OptionGroups

### ISSUE THREAD

**Issue by etosch** [prakhar1989/react-surveyman#12]
In some surveys, there are options that get used over and over again, especially if the survey consists of many questions in a Likert scal, e.g.:

How strongly do you agree that chocolate is the best ice cream? 
-  Agree Strongly.
-  Agree
-  Disagree
-  Disagree Strongly. 

It would be very convenient if we had separate window for the most popular ones. You would then need to add a `copyOption` action, or represent the cached option as a generator (looks like it would be similar to the [DraggableBlock](https://github.com/prakhar1989/react-surveyman/blob/master/js/components/DraggableBlock.js#L6))

**Comment by prakhar1989** [comment]
You mean an option group, right? I was planning to have a similar area for stored Option groups (below the toolbox for example) where users can save set of options as one block and then drag them in one go. The options can be persisted in localStorage at the start. I plan to get working on this as soon as treeview and other easier features stabilize.

**Comment by etosch** [comment]
Sounds good!

**Comment by prakhar1989** [comment]
@etosch : Quick question - Is it fair to assume that the question ids generated in a survey are unique across the survey (across blocks, subblocks etc.)? I've not yet looked at how those are generated. Can you also point me to the code where those are generated as I need to do the same in this project?

**Comment by etosch** [comment]
There is an internal id that is uniquely generated, but the id that’s used in surveyman.js takes the form <prefix>_<row>_<col> from the csv implementation. This allowed us to debug more easily (e.g., ensure that the randomization was occurring properly), to look up the value of the id in the original csv, etc. 

When re-using options, as we’ve been discussing, they should each have a unique id.

**Comment by prakhar1989** [comment]
That sounds good. However, when the survey is generated from react-surveyman how should I instantiate new types with IDs since I don't have a `row` or `col`?

**Comment by etosch** [comment]
“col” should be the same for all Options. “row” is computed from the existing options associated with the containing question — just set it to be the size of the current list of options.

**Comment by prakhar1989** [comment]
Ok. I'll try and figure this out and get back to you if I'm stuck.
