### ISSUE TITLE
Weekly Updates

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/react-surveyman#2]
Hi @etosch, as a part of the weekly update, I'm creating an issue to highlight the key updates. Using GH issues will make it easier to track our discussion & your feedback. If you prefer, google groups / email for this task - let me know. 

This week, I've completed two major pieces of functionality - 
- [Flux](http://facebook.github.io/flux/) architecture - Used the [Reflux](https://github.com/spoike/refluxjs) library to implement the flux architecure in the application. Instead of top-level component acting as a controller and view both, all data changes happen in the `SurveyStore` which is responsible for mutating the survey JSON object. The views are responsible for catching user inputs and calling the relevant actions.

```
╔═════════╗       ╔════════╗       ╔═════════════════╗
║ Actions ║──────>║ Stores ║──────>║ View Components ║
╚═════════╝       ╚════════╝       ╚═════════════════╝
     ^                                      │
     └──────────────────────────────────────┘
```
- DropTargets: Replaced the existing `DropZone` with drop targets on each type e.g. every _Question_ is  now a valid drop target for all _Option_ types. This makes is possible to add any item type on any valid object instead of the earlier stack-like-additions. When a widget is picked from the Toolbox, the appropriate item type is highlighted for the user.

These changes can be tested on [my website](http://prakhar.me/react-surveyman).

Looking forward to your feedback.

**Comment by etosch** [comment]
Looks great! I'm going to tag @sarackingsley in this post, since she has a keen eye for usability.
