### ISSUE TITLE
Ability to Save / Load surveys

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/react-surveyman#23]
- [x] Save survey to [localStorage](https://github.com/tsironis/lockr)
- [x] Clear survey
- [x] Load survey from localstorage
- [x] Provide the user the option to load from localstorage
- [x] Load survey from a file
- [ ] Download survey to a file

**Comment by prakhar1989** [comment]
Idea: When a `survey` key is detected in localStorage give the user an option to load the survey.

**Comment by etosch** [comment]
You're keeping them in browser local storage, right?

## 

  Emma Tosch
  etosch@fastmail.fm

On Thu, Jul 30, 2015, at 01:05 PM, Prakhar Srivastav wrote:

> Idea: When a survey key is detected in localStorage give the user an option to load the survey.
> 
> —
> Reply to this email directly or view it on GitHub[1]. 

Links:
1. https://github.com/prakhar1989/react-surveyman/issues/23#issuecomment-126463674

**Comment by prakhar1989** [comment]
Yes!

**Comment by prakhar1989** [comment]
@etosch Almost there!

![image](https://cloud.githubusercontent.com/assets/649249/9054445/19e4ceae-3a9f-11e5-91c2-8c271153ecf9.png)
