### ISSUE TITLE
Allow items to be positioned arbitrarily when being dropped

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/react-surveyman#24]
![dnd-new](https://cloud.githubusercontent.com/assets/649249/8225280/2c55dd76-15b0-11e5-9d50-0f9be3c8843a.gif)

This a use-case in which drag-and-drop really shines.

**Comment by prakhar1989** [comment]
Come to think of it, @etosch pointed out earlier that react-surveyman should make it explicit that the items in the survey will be unordered (random). This feature runs counter-intuitive to that philosophy as allowing users to place an item at a specific position will lead them to believe that the order is relevant.

Since the natural order of items when being added is to be unordered, the items can just be appended to 
the parent container. As a result, I believe this feature is not required and can be dropped. 

@etosch - What do you think about this?

**Comment by etosch** [comment]
In general I agree with this assessment. @sckingsley -- do you have any comments or insight on this?

I do have one concern: It would be nice to pull questions up to the top for ease of editing. This however is minor.

**Comment by prakhar1989** [comment]
> It would be nice to pull questions up to the top for ease of editing

@etosch: Can you please elaborate a bit more on this? As of now you can edit questions simply by double clicking on them. In a long survey, you can use the minimap to call them to focus and then do the same.

**Comment by etosch** [comment]
If someone is writing the survey and questions are added to end and they 
want to keep it in view at the top, or compare with another question, 
they might want to move that question to a different position in the 
survey for reasons pertaining to UX stuff, rather than survey semantics.

**Comment by prakhar1989** [comment]
Ah great idea. So instead of pushing the question at the bottom, I'll add it at the 0th index?

**Comment by etosch** [comment]
Sounds good!
