### ISSUE TITLE
drop broke in safari

### ISSUE THREAD

**Issue by etosch** [prakhar1989/react-surveyman#25]
@jvilk says nothing happens when dragging and dropping a block. Here's a screen shot from when I try to repeat:

![screen shot 2015-06-21 at 5 19 30 pm](https://cloud.githubusercontent.com/assets/508630/8274004/d01b9dfc-1839-11e5-85cf-d266ead47ad3.png)

**Comment by prakhar1989** [comment]
One of the reasons why this error / warning is being generated is due to the mapping over the Immutable collection. I tried isolating the issue on the minimap and this is what I've found - http://stackoverflow.com/questions/31195321/immutable-js-mapping-over-keys-in-safari.

**Comment by jvilk** [comment]
Hmm? The React warning in your SO post makes sense.

> _Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child._

``` javascript
    var items = Immutable.fromJS([
      {id: 1, val: "foo"},
      {id: 2, val: "bar"},
      {id: 3, val: "moo"},
      {id: 4, val: "baz"}
    ]);

    var tree = items.map(function(item, i) {
      // This is a keyed object. https://facebook.github.io/react/docs/create-fragment.html
      return <p key={i}>{item.get('val')}</p>
    });
    // Tree is composed of keyed objects.

    return (
        // You are making tree a child of div. Tree is composed of keyed objects. Therefore, you are passing
        // a keyed object as a child of this div without wrapping it in createFragment.
        <div className="tree-view">
            {tree}
        </div>
    )
```

**Comment by prakhar1989** [comment]
@jvilk: Right.. but the mapping over Immutable sequences should only pick up the elements and not the object properties. Weirdly, I'm unable to replicate this in [jsbin](http://jsbin.com/vipirahohi/edit?js,output).. so some issue in the application only. Somehow, this is working fine in Chrome / Firefox.
