### ISSUE TITLE
Broken package

### ISSUE THREAD

**Issue by mohamedRhaiem** [prakhar1989/react-surveyman#34]
I`m trying to run this app but without success,the $npm run start command return this log :

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files (x86)\nodejs\\node.exe',
1 verbose cli   'C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-surveyman@0.0.1
6 info start react-surveyman@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info react-surveyman@0.0.1 Failed to exec start script
9 verbose stack Error: react-surveyman@0.0.1 start: `./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --port 8090`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid react-surveyman@0.0.1
11 verbose cwd C:\Users\Dev\react-surveyman
12 error Windows_NT 6.3.9600
13 error argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "run" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error react-surveyman@0.0.1 start: `./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --port 8090`
17 error Exit status 1
18 error Failed at the react-surveyman@0.0.1 start script './node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --port 8090'.
18 error This is most likely a problem with the react-surveyman package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --port 8090
18 error You can get their info via:
18 error     npm owner ls react-surveyman
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Any suggestion ?

**Comment by prakhar1989** [comment]
I think the issue is because you're on windows and my node scripts are not windows friendy. The `./` syntax works on Unix machine  and is probably the cause of issue. I'm not quite sure how you can run `node` scripts in Windows.

Can you try running the following command in Windows and see what the output is?
 `./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --port 8090` 

If this fails, try 
`node  ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --port 8090`

**Comment by mohamedRhaiem** [comment]
yeah,that is the error, this command return " '.' is not recognized as an internal or external command, operable program or batch file."

**Comment by prakhar1989** [comment]
Ah ok.. Expected. Running the command like so - 

`C:\Program Files (x86)\nodejs\node.exe \node_modules\webpack-dev-server\bin\webpack-dev-server.js --progress --colors --port 8090`.

Basically we need to figure out how to run node scripts in Windows

**Comment by mohamedRhaiem** [comment]
know,the error was changed,
module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\node_modules\webpack-dev-server\bin\webpack-dev-se
rver.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

can be provided by the same issue unrecognized node script with windows ??

**Comment by prakhar1989** [comment]
Sorry.. my bad.. try it without the starting slash.. 
`node node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --colors --port 8090`

**Comment by mohamedRhaiem** [comment]
issue resolved,thank you some much,only a last question,this app can run on  web browser as a Javascript in html page...,if not,can I try a migration ???

**Comment by prakhar1989** [comment]
Great! It actually runs as a single JS file in a HTML page.. you can view the [demo](http://prakhar.me/react-survayman). What do you want to migrate it to? Either ways, feel free to use it as you like :grin:
