### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by AlanVerbner** [prakhar1989/react-surveyman#36]
Hey! this looks great. Congratulations.

I wasn't able to find license reference in readme.md. Does package.json one ("license": "MIT") applies to the project?

Thanks in advance!

**Comment by prakhar1989** [comment]
Thanks Alan! Glad you liked it!

@etosch: Want to chime in?

**Comment by etosch** [comment]
The SurveyMan license is CRAPL (http://matt.might.net/articles/crapl/). All jokes aside, the idea is that if you use it, you need to cite the paper
`
@inproceedings{tosch2014surveyman,
  title={Surveyman: Programming and automatically debugging surveys},
  author={Tosch, Emma and Berger, Emery D},
  booktitle={Proceedings of the 2014 ACM International Conference on Object Oriented Programming Systems Languages \& Applications},
  pages={197--211},
  year={2014},
  organization={ACM}
}
`

MIT is fine for @prakhar1989's work, although he might want to consider something that requires citation.

**Comment by AlanVerbner** [comment]
LOL...i will check it out ... thaks @prakhar1989 @etosch for the quick answer.
