### ISSUE TITLE
Componentize CSS

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/react-surveyman#7]
Separate CSS into state-based and appearance only. Move the state-based part into JSX. Refer to the [awesome talk](https://www.youtube.com/watch?v=ERB1TJBn32c) at React Europe by Micheal Chan.

**Comment by prakhar1989** [comment]
Refer [here](https://github.com/petehunt/jsxstyle) for best practices

**Comment by prakhar1989** [comment]
Instead of a global CSS stylesheet, modularize CSS styles. [Examples](https://github.com/MicheleBertoli/css-in-js)

**Comment by chantastic** [comment]
very cool. excited to hear your feedback on how this works for you :)

**Comment by prakhar1989** [comment]
Will definitely keep you posted! Thank you for the great talk!
